l_english:
 pmg_base_building_synthetic_oil_plants:0 "Synthetic Oil"
 pmg_base_building_synthetic_rubber_plants:0 "Synthetic Rubber"
 pm_synth_oil_production:0 "Synthetic Oil Production"
 pm_improved_synth_oil_production:0 "Improved Synthetic Oil Production"
 pm_synth_rubber_production:0 "Synthetic Rubber"

 pmg_ownership_capital_building_synthetic_oil_plants:0 "Ownership"
 pmg_ownership_capital_building_synthetic_rubber_plants:0 "Ownership"