l_braz_por:
  pmg_base_building_synthetic_oil_plants:0 "Óleo Sintético"
 pmg_base_building_synthetic_rubber_plants:0 "Borracha Sintética"
 pm_synth_oil_production:0 "Produção de Óleo Sintético"
 pm_improved_synth_oil_production:0 "Produção de Óleo Sintético Melhorado"
 pm_synth_rubber_production:0 "Produção de Borracha Sintética"

 pmg_ownership_capital_building_synthetic_oil_plants:0 "Propriedade Privada"
 pmg_ownership_capital_building_synthetic_rubber_plants:0 "Propriedade Privada"